[general]
shuffle_caption = false
caption_dropout_rate = 0.0
token_warmup_step = 0
caption_tag_dropout_rate = 0.0
caption_extension = ".txt"
keep_tokens = 1
seed = 47

[model]
pretrained_model_name_or_path = "../models/sd_xl_base_1.0.safetensors"
vae = "../models/sdxl.vae.safetensors"

[training]
resolution = "1024,1024"
batch_size = 1
learning_rate = 0.0001
lr_scheduler = "cosine"
lr_warmup_steps = 100
max_train_epochs = 15
optimizer_type = "AdamW8bit"
mixed_precision = "bf16"
gradient_checkpointing = true
clip_skip = 2
network_module = "networks.lora"
network_dim = 32
network_alpha = 16
save_precision = "bf16"
save_every_n_epochs = 1
network_train_unet_only = true
cache_text_encoder_outputs = true   # 캐시 유지

[folders]
train_data_dir = "../dataset/training"
output_dir = "../output_models"
logging_dir = "../logs"

[advanced]
bucket_reso_steps = 64
bucket_no_upscale = true
xformers = true
cache_latents = true
cache_latents_to_disk = true
min_bucket_reso = 512
max_bucket_reso = 2048
